---
title: "PM 566 Final Project"
author: "Brandyn Ruiz"
date: "11/13/2020"
output: html_document
---

```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(data.table)
library(httr)
library(rjson)
library(ggplot2)
library(usmap)
library(RColorBrewer)
library(rgdal)
library(ggrepel)
library(plotly)
```


## Covid Cases within the States
```{r Covid Github, message=FALSE, warning=FALSE}
download.file("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv", "time_series_covid19_confirmed_US.csv", method="libcurl", timeout = 60)

covidGithub <- data.table::fread("time_series_covid19_confirmed_US.csv")
```

```{r, echo=FALSE}
# Applying filter to only select covid confirmed cases in California
covidGithub <- covidGithub%>%
  filter(Province_State == 'California')%>%
  rename(county = Admin2)

covidGithub <- covidGithub[ !(covidGithub$county %in% c('Unassigned', 'Out of CA')), ]
```

```{r Melting Covid Data Set, message = FALSE, warning = FALSE, echo=FALSE}
# Attempt to melt covid to long format
covidGithubmelt <- melt(covidGithub, id = 1:11, variable.name = 'Date', variable.factor = FALSE,
                        value.name = 'Confirmed')
covidGithubmelt$Date <- as.Date(covidGithubmelt$Date, format = "%m/%d/%y")

# Group by counties and order by date of dataset print out
covidGithubmelt <- covidGithubmelt%>%
  group_by(county)%>%
  arrange(Date, .by_group = TRUE)
```

```{r New Cases Varible, warning=FALSE, echo=FALSE}
# format the state variable
county_list <- unique(covidGithubmelt$county)
covidGithubmelt$county <- factor(covidGithubmelt$county, levels = county_list)

# Add variables for new_cases:
for (i in 1:length(county_list)) {
  cvd_subset = subset(covidGithubmelt, county == county_list[i])
  cvd_subset = cvd_subset[order(cvd_subset$Date),]

  # add starting level for new cases and deaths
  cvd_subset$new_cases = covidGithubmelt$Confirmed[1]

  for (j in 2:nrow(cvd_subset)) {
    cvd_subset$new_cases[j] =  cvd_subset$Confirmed[j] - cvd_subset$Confirmed[j-1] 
  }

  # include in main dataset
  covidGithubmelt$new_cases[covidGithubmelt$county == county_list[i]] = cvd_subset$new_cases
}
```

### Incidence Cases Across the Pandemic 
```{r COVID Visual by County, warning=FALSE, message=FALSE}
p1<-ggplot(covidGithubmelt, aes(Date, new_cases, color = county))+
  geom_line()+
  geom_point(size = .5, alpha = 0.5)+
  labs(title = 'Incidences of Covid Cases in California by County', y = 'New cases', color = 'County')
ggplotly(p1)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# Adjusting Merge data set to ggmap setting with only FIPS and Confirmed variables 
mapdf <- covidGithubmelt%>%
  filter(Date == as.Date(max(Date)))%>%
  select(FIPS, Date, new_cases, Confirmed)%>%
  distinct()%>%
  rename(fips = FIPS)
```

## Incidence Cases
```{r Spatial Visualization of COVID by County, warning=FALSE}
incidence <- plot_usmap(data = mapdf, values='new_cases', include = 'CA')+
  scale_fill_continuous(low = 'white', high = 'red', name = 'Confirmed Cases', label = scales::comma)+
  labs(title = 'Incidence Cases by California County',
       subtitle = 'Source: Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE)',
       # caption = 'As of 11/12/2020')+
       caption = paste('As of ', as.Date(max(mapdf$Date))))+
  theme(plot.title = element_text(hjust = 0.5, vjust = 0.25, size = 18), legend.position = "right",
        legend.title = element_text(size = 14), legend.text = element_text(size = 12))
```

## Total Confirmed Cases
```{r Grand Total Confirmed Cases, warning=FALSE}
prevalence <- plot_usmap(data = mapdf, values='Confirmed', include = 'CA')+
  scale_fill_continuous(low = 'white', high = 'red', name = 'Confirmed Cases', label = scales::comma)+
  labs(title = 'Total Cases in California by County',
       subtitle = 'Source: Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE)',
       caption = paste('As of ', as.Date(max(mapdf$Date))))+
  theme(plot.title = element_text(hjust = 0.5, vjust = 0.25, size = 18), legend.position = "right",
        legend.title = element_text(size = 14), legend.text = element_text(size = 12))
```

## Exploration of Covid Cases within California {.tabset}

### Incidence Figure 1
```{r, warning=FALSE, message=FALSE}
ggplotly(incidence)
```

### Prevalence Figure 2
```{r, warning=FALSE, message=FALSE}
prevalence
```

## {-}

## US Census data of California
```{r Population Visualizations, warning=FALSE, message=FALSE}
CAcensus <- read_csv("data/cc-est2019-alldata-06.csv")
```

```{r, echo=FALSE}
# 2019 Population Estimate of each CA county from US Census
CApop <- CAcensus%>%
  filter(YEAR == 12, AGEGRP == 0)

CApop$COUNTY <- paste0(6, CApop$COUNTY)

# Spatial map of CA county population densities
Popmapdf <- CApop%>%
  select(COUNTY, TOT_POP)%>%
  rename(fips = COUNTY)
```

### County Populations Within California
```{r, warning=FALSE}
plot_usmap(data = Popmapdf, values='TOT_POP', include = 'CA')+
  #scale_fill_distiller(type = "seq", palette = "Spectral", direction = -1, name = "County Populations")+
  scale_fill_continuous(low = 'white', high = 'blue', name = 'Population', label = scales::comma)+
  labs(title = '2019 County Population Estimates', subtitle = 'Source: US Census')+
  theme(plot.title = element_text(hjust = 0.5, vjust = 0.25, size = 18), legend.position = "right",
        legend.title = element_text(size = 14), legend.text = element_text(size = 12))
```

```{r COVID vs Population Density, echo=FALSE}
# Applying filter for the most current covid data
covidGithubmelt_today <- covidGithubmelt%>%
  filter(Date == as.Date(max(Date)))

CApop_today <- CApop%>%
  rename(FIPS = COUNTY)

# Merging the grand total of covid cases with county population
cvd_pop<- merge(covidGithubmelt_today, CApop_today, by = 'FIPS')

cvd_pop$per100k = as.numeric(format(round(cvd_pop$Confirmed/(cvd_pop$TOT_POP/100000),1),
                                      nsmall=1))
```


### Running Total of Confirmed Cases by Population of Counties
```{r, warning=FALSE, message=FALSE}
# Adding hoverinfo
cvd_pop%>% 
  plot_ly(x = ~TOT_POP, y = ~Confirmed,
          type = 'scatter', mode = 'markers', color = ~county,
          size = ~TOT_POP, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(county, ":", sep=""), paste(" Cases per 100k: ", per100k, sep=""),
                         paste(' Population: ', TOT_POP, sep=""), sep = "<br>"))%>%
  layout(title = "Covid Cases vs Population of Each County",
                  yaxis = list(title = "Cases per 100k"), xaxis = list(title = "Population"))
```

## Air Quality Index
```{r, message=FALSE}
# Daily AQI for every county in California
csvAQI_data <- read_csv("data/ad_viz_plotval_data.csv")
```

```{r, echo=FALSE, eval=FALSE}
csvAQI_data$Date <- as.Date(csvAQI_data$Date, format = "%m/%d/%Y")

# Test to see if counties have current dates
csvAQI_data%>%
  group_by(COUNTY)%>%
  summarise(MinDate = min(Date), MaxDate = max(Date))%>%
  knitr::kable()
```

```{r AQi Visual Setup, echo=FALSE}
csvAQI_data$Date <- as.Date(csvAQI_data$Date, format = "%m/%d/%y")

# Group by counties and order by date of dataset print out
csvAQI_data <- csvAQI_data%>%
  group_by(COUNTY)%>%
  arrange(Date, .by_group = TRUE)
```

```{r AQI Setup, echo=FALSE}
AQI <- csvAQI_data%>%
  select(Date, COUNTY, `Daily Mean PM2.5 Concentration`, DAILY_AQI_VALUE, COUNTY_CODE)%>%
  group_by(Date, COUNTY)%>%
  mutate(MeanPM2.5 = mean(`Daily Mean PM2.5 Concentration`), MeanAQI = mean(DAILY_AQI_VALUE))

AQI <- AQI%>%
  select(Date, COUNTY, COUNTY_CODE, MeanPM2.5, MeanAQI)%>%
  distinct()
```


```{r AQI Visual}
#Visual is much better
# x-axis every other county
# csvAQI_data%>%
#   plot_ly(x = ~COUNTY, y = ~DAILY_AQI_VALUE, type = 'box', color = ~COUNTY)%>%
#   layout(title = 'Air Quality by California County', yaxis = list(title = 'AQI Value'),
#          xaxis = list(title = 'County'))

AQI%>%
  plot_ly(x = ~COUNTY, y = ~MeanAQI, type = 'box', color = ~COUNTY)%>%
  layout(title = 'Air Quality by California County', yaxis = list(title = 'AQI Value'),
         xaxis = list(title = 'County'))

#Could save for another visual with Covid cases on AQI daily for LA County
# AQI%>%
#   filter(COUNTY == 'Los Angeles')%>%
#   plot_ly(x = ~Date, y = ~MeanAQI,
#           type = 'scatter', mode = 'line',
#           hoverinfo = 'text',
#           text = ~paste( paste(COUNTY, ":", sep=""), paste(' Avg AQI: ', MeanAQI, sep=""),
#            paste(" Avg PM 2.5: ", MeanPM2.5, sep=""), sep = "<br>"))%>%
#   layout(title = 'LA County', yaxis = list(title = 'AQI Value'),
#          xaxis = list(title = 'Date'))
```
